"use client";

import Cookies from "js-cookie";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = usePathname();
  const defaultToken =
    "";
  useEffect(() => {
    if (Cookies.get("isLogin") == null || Cookies.get("isLogin") === "false") {
      Cookies.set("accessToken", defaultToken);
      Cookies.set("isLogin", "false");;
    }
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* <div> */}
          {/* <Script src="https://docs.opencv.org/4.5.0/opencv.js" strategy="beforeInteractive"/> */}
          
          {children}
        {/* </div> */}
      </body>

    </html>
  );
}
